language: java

java:
  - 1.6
install:
 - chmod +x gradlew

notifications:
  email:
    recipients:
      - jordandes@gmail.com
    on_success: always
    on_failure: always

script:
  "./gradlew check -i"