language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk6
  - openjdk8
  - openjdk7
  - openjdk6

install:
 - chmod +x gradlew

notifications:
  email:
    recipients:
      - jordandes@gmail.com
    on_success: always
    on_failure: always

script:
  "./gradlew check -i"